#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
from classes.vault import Vault

# Add the script version: 0.1
__version__ = "0.1"

# Constants indicating default values for parameters
DEFAULT_VERBOSE = True

def main():
    # Configure command line arguments
    parser = argparse.ArgumentParser(
        description='Obsidian Notes Manager',
        epilog=f'Version: {__version__}'
    )

    parser.add_argument('-v', '--verbose', 
                       action='store_true',
                       help='detailed execution information (default: enabled)')
   
    args = parser.parse_args()

    # If -v is not used, use the default value; if -v is used, use True
    verbose = args.verbose if args.verbose else DEFAULT_VERBOSE
    
    if verbose:
        parser.print_help()
        # Create vault instance and print it
        vault = Vault()
        print(vault)

if __name__ == "__main__":
    main()
